# Alembic Configuration File
# the output encoding used to render the Mako templates
# Note that Mako templates have a default output encoding of 'utf-8'
output_encoding = utf-8

sqlalchemy.url = driver://user:password@localhost/dbname

# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(created_date)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepended_sys_path = .

# timezone to use when rendering the date
# within the "create date" field. When set to the value 'UTC', it
# will also disable UTC representation of datetime objects.
# If left blank, this value will be interpreted as a SQL 'naive' datetime
# and will render the current date/time as accepted by the database dialect.
# Can be an instance of `datetime.tzinfo`, a string, or 'UTC'.
sqlalchemy.timezone =

# max length of characters to apply to the
# "slug" field.
# set to 0 to disable, None to read the default
# retained for the 0.6 to 0.7 migration
sqlalchemy_string_length = 255

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# This will attach to the context.configure()
revision.process_revision_directives = null

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine,sqlalchemy.pool,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_sqlalchemy.pool]
level = WARN
handlers =
qualname = sqlalchemy.pool

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
